// <auto-generated />
namespace HappySitter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addcostcolumnonReservationsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcostcolumnonReservationsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003282024301_add cost column on Reservations Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
